// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerServiceClient interface {
	AddCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error)
	UpdateName(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error)
	UpdateNumber(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error)
	DeleteCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error)
	GetRebelds(ctx context.Context, in *LeiaMessage, opts ...grpc.CallOption) (*BrokerReadMessage, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) AddCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error) {
	out := new(BrokerWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.BrokerService/AddCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) UpdateName(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error) {
	out := new(BrokerWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.BrokerService/UpdateName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) UpdateNumber(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error) {
	out := new(BrokerWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.BrokerService/UpdateNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) DeleteCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*BrokerWriteMessage, error) {
	out := new(BrokerWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.BrokerService/DeleteCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetRebelds(ctx context.Context, in *LeiaMessage, opts ...grpc.CallOption) (*BrokerReadMessage, error) {
	out := new(BrokerReadMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.BrokerService/GetRebelds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility
type BrokerServiceServer interface {
	AddCity(context.Context, *InformantMessage) (*BrokerWriteMessage, error)
	UpdateName(context.Context, *InformantMessage) (*BrokerWriteMessage, error)
	UpdateNumber(context.Context, *InformantMessage) (*BrokerWriteMessage, error)
	DeleteCity(context.Context, *InformantMessage) (*BrokerWriteMessage, error)
	GetRebelds(context.Context, *LeiaMessage) (*BrokerReadMessage, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServiceServer struct {
}

func (UnimplementedBrokerServiceServer) AddCity(context.Context, *InformantMessage) (*BrokerWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCity not implemented")
}
func (UnimplementedBrokerServiceServer) UpdateName(context.Context, *InformantMessage) (*BrokerWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateName not implemented")
}
func (UnimplementedBrokerServiceServer) UpdateNumber(context.Context, *InformantMessage) (*BrokerWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNumber not implemented")
}
func (UnimplementedBrokerServiceServer) DeleteCity(context.Context, *InformantMessage) (*BrokerWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCity not implemented")
}
func (UnimplementedBrokerServiceServer) GetRebelds(context.Context, *LeiaMessage) (*BrokerReadMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRebelds not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_AddCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).AddCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.BrokerService/AddCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).AddCity(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_UpdateName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).UpdateName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.BrokerService/UpdateName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).UpdateName(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_UpdateNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).UpdateNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.BrokerService/UpdateNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).UpdateNumber(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_DeleteCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).DeleteCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.BrokerService/DeleteCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).DeleteCity(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetRebelds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeiaMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetRebelds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.BrokerService/GetRebelds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetRebelds(ctx, req.(*LeiaMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoStarWars.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCity",
			Handler:    _BrokerService_AddCity_Handler,
		},
		{
			MethodName: "UpdateName",
			Handler:    _BrokerService_UpdateName_Handler,
		},
		{
			MethodName: "UpdateNumber",
			Handler:    _BrokerService_UpdateNumber_Handler,
		},
		{
			MethodName: "DeleteCity",
			Handler:    _BrokerService_DeleteCity_Handler,
		},
		{
			MethodName: "GetRebelds",
			Handler:    _BrokerService_GetRebelds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuffers/starwars.proto",
}

// FulcrumServiceClient is the client API for FulcrumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FulcrumServiceClient interface {
	AddCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error)
	UpdateName(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error)
	UpdateNumber(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error)
	DeleteCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error)
	GetRebelds(ctx context.Context, in *LeiaMessage, opts ...grpc.CallOption) (*FulcrumReadMessage, error)
}

type fulcrumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFulcrumServiceClient(cc grpc.ClientConnInterface) FulcrumServiceClient {
	return &fulcrumServiceClient{cc}
}

func (c *fulcrumServiceClient) AddCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error) {
	out := new(FulcrumWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.FulcrumService/AddCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) UpdateName(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error) {
	out := new(FulcrumWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.FulcrumService/UpdateName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) UpdateNumber(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error) {
	out := new(FulcrumWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.FulcrumService/UpdateNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) DeleteCity(ctx context.Context, in *InformantMessage, opts ...grpc.CallOption) (*FulcrumWriteMessage, error) {
	out := new(FulcrumWriteMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.FulcrumService/DeleteCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) GetRebelds(ctx context.Context, in *LeiaMessage, opts ...grpc.CallOption) (*FulcrumReadMessage, error) {
	out := new(FulcrumReadMessage)
	err := c.cc.Invoke(ctx, "/protoStarWars.FulcrumService/GetRebelds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FulcrumServiceServer is the server API for FulcrumService service.
// All implementations must embed UnimplementedFulcrumServiceServer
// for forward compatibility
type FulcrumServiceServer interface {
	AddCity(context.Context, *InformantMessage) (*FulcrumWriteMessage, error)
	UpdateName(context.Context, *InformantMessage) (*FulcrumWriteMessage, error)
	UpdateNumber(context.Context, *InformantMessage) (*FulcrumWriteMessage, error)
	DeleteCity(context.Context, *InformantMessage) (*FulcrumWriteMessage, error)
	GetRebelds(context.Context, *LeiaMessage) (*FulcrumReadMessage, error)
	mustEmbedUnimplementedFulcrumServiceServer()
}

// UnimplementedFulcrumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFulcrumServiceServer struct {
}

func (UnimplementedFulcrumServiceServer) AddCity(context.Context, *InformantMessage) (*FulcrumWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCity not implemented")
}
func (UnimplementedFulcrumServiceServer) UpdateName(context.Context, *InformantMessage) (*FulcrumWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateName not implemented")
}
func (UnimplementedFulcrumServiceServer) UpdateNumber(context.Context, *InformantMessage) (*FulcrumWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNumber not implemented")
}
func (UnimplementedFulcrumServiceServer) DeleteCity(context.Context, *InformantMessage) (*FulcrumWriteMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCity not implemented")
}
func (UnimplementedFulcrumServiceServer) GetRebelds(context.Context, *LeiaMessage) (*FulcrumReadMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRebelds not implemented")
}
func (UnimplementedFulcrumServiceServer) mustEmbedUnimplementedFulcrumServiceServer() {}

// UnsafeFulcrumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulcrumServiceServer will
// result in compilation errors.
type UnsafeFulcrumServiceServer interface {
	mustEmbedUnimplementedFulcrumServiceServer()
}

func RegisterFulcrumServiceServer(s grpc.ServiceRegistrar, srv FulcrumServiceServer) {
	s.RegisterService(&FulcrumService_ServiceDesc, srv)
}

func _FulcrumService_AddCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).AddCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.FulcrumService/AddCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).AddCity(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_UpdateName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).UpdateName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.FulcrumService/UpdateName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).UpdateName(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_UpdateNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).UpdateNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.FulcrumService/UpdateNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).UpdateNumber(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_DeleteCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformantMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).DeleteCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.FulcrumService/DeleteCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).DeleteCity(ctx, req.(*InformantMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_GetRebelds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeiaMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).GetRebelds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoStarWars.FulcrumService/GetRebelds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).GetRebelds(ctx, req.(*LeiaMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// FulcrumService_ServiceDesc is the grpc.ServiceDesc for FulcrumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FulcrumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoStarWars.FulcrumService",
	HandlerType: (*FulcrumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCity",
			Handler:    _FulcrumService_AddCity_Handler,
		},
		{
			MethodName: "UpdateName",
			Handler:    _FulcrumService_UpdateName_Handler,
		},
		{
			MethodName: "UpdateNumber",
			Handler:    _FulcrumService_UpdateNumber_Handler,
		},
		{
			MethodName: "DeleteCity",
			Handler:    _FulcrumService_DeleteCity_Handler,
		},
		{
			MethodName: "GetRebelds",
			Handler:    _FulcrumService_GetRebelds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuffers/starwars.proto",
}
